# fly.toml app configuration file generated for autumn-dust-7523 on 2023-08-28T20:03:27+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "autumn-dust-7523"
primary_region = "ams"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[env]
  PORT = "3000"

[build]
  [build.args]
    NODE_VERSION = "16.20.2"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
